# Generated by Django 6.0.2 on 2026-02-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls_storage',
            name='short_url',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
