# Generated by Django 6.0.2 on 2026-02-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_file', '0002_alter_urls_storage_short_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLSTORAGE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.CharField()),
                ('short_code', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('click_count', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='urls_storage',
        ),
        migrations.AddIndex(
            model_name='urlstorage',
            index=models.Index(fields=['short_code'], name='main_file_u_short_c_571da5_idx'),
        ),
    ]
