# Generated by Django 6.0.2 on 2026-02-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_file', '0003_urlstorage_delete_urls_storage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlstorage',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
    ]
