# Generated by Django 6.0.2 on 2026-02-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_file', '0004_alter_urlstorage_click_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlstorage',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urlstorage',
            name='short_code',
            field=models.CharField(max_length=12),
        ),
    ]
